# Generated by Django 5.2.6 on 2026-09-05 09:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Bahar Barghbani', max_length=120)),
                ('professional_title', models.CharField(blank=True, max_length=180)),
                ('major', models.CharField(blank=True, max_length=180)),
                ('institution', models.CharField(blank=True, max_length=180)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('short_bio', models.TextField(blank=True, help_text='Two or three sentences for the homepage introduction.')),
                ('about', models.TextField(blank=True, help_text='Your longer academic and professional story.')),
                ('research_interests', models.TextField(blank=True, help_text='Enter one research interest per line.')),
                ('personal_note', models.TextField(blank=True, help_text='A short personal detail, such as hobbies or what motivates you.')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('scholar_url', models.URLField(blank=True, verbose_name='Google Scholar URL')),
                ('orcid_url', models.URLField(blank=True, verbose_name='ORCID URL')),
                ('cv', models.FileField(blank=True, help_text='Upload your current CV as a PDF.', upload_to='cv/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Academic profile',
                'verbose_name_plural': 'Academic profile',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=240, unique=True)),
                ('summary', models.TextField(help_text='A short explanation for project cards.')),
                ('description', models.TextField(blank=True, help_text='The problem, your approach, and the outcome.')),
                ('technologies', models.CharField(blank=True, help_text='Comma-separated tools or technologies.', max_length=300)),
                ('image', models.ImageField(blank=True, upload_to='project_images/')),
                ('repository_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('display_order', '-created_at', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=240, unique=True)),
                ('field', models.CharField(blank=True, help_text='The research area or discipline.', max_length=160)),
                ('summary', models.TextField(help_text='A short explanation for research cards.')),
                ('abstract', models.TextField(blank=True, help_text='A longer description shown on the research detail page.')),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('preprint', 'Preprint'), ('published', 'Published')], default='ongoing', max_length=20)),
                ('venue', models.CharField(blank=True, help_text='Journal, conference, lab, or institution.', max_length=220)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('collaborators', models.CharField(blank=True, max_length=300)),
                ('publication_url', models.URLField(blank=True)),
                ('code_url', models.URLField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Research',
                'ordering': ('display_order', '-year', 'title'),
            },
        ),
    ]
