# Generated by Django 5.2.4 on 2025-08-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_name',
            field=models.CharField(default='Post', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='post_preview',
            field=models.CharField(default='Preview', max_length=100),
        ),
    ]
