# Generated by Django 5.2.4 on 2025-08-02 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_post_name_post_post_preview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_name',
            new_name='post_title',
        ),
    ]
