# Generated by Django 5.2.4 on 2025-08-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_post_name_post_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_preview',
            field=models.CharField(default='Preview', max_length=200),
        ),
    ]
