# Generated by Django 5.2.6 on 2025-10-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_preview',
            field=models.CharField(default='Preview', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_title',
            field=models.CharField(default='Post', max_length=100),
        ),
    ]
