# Generated by Django 5.2.4 on 2025-10-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_content_alter_post_post_preview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(default='Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(default='Anonymous', max_length=50),
        ),
    ]
